name: on Create workflow

on:
  create:


jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo `Hello word from ${GITHUB_REF##*/}`
        shell: bash
      
