name: s3 upload workflow

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "* * * * 1-5"

  # workflow_run:
  #   workflows: ["simple workflow"]
  #   types: [completed]
  #   branches:
  #     - main

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true
env:
  AWS_REGION: MY_AWS_REGION

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: ".github/actions/nodejs"
        with:
          inputField: "very very secret key"

  deploy:
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200

      - name: download build artifacts to upload
        uses: actions/download-artifact@v3
        with:
          name: buildFiles

      - name: deploy the build files
        if: ((github.event.action == 'closed' && github.event.pull_request.merged == true))
        run: aws s3 sync ./ ./
