name: Nodejs Matrix workflow

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs-version: [12, 14, 16]
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: Install required Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "{{ matrix.nodejs-version }}"

      - name: install node modules
        run: npm ci
        shell: bash

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      - name: run tests
        run: ./.github/scripts/test.sh
        shell: bash
